### ISSUE TITLE
Use Nodejs vars in Python

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/pixiedust_node#12]
Today, I can use `store` to save Nodejs vars for use in Python cells, but I can't do the opposite. That is, I can't access Python vars in `%%node` cells.

**Comment by glynnbird** [comment]
So the syntax for "store" is like this:

```js
%%node
var x = [ { a:1, b:2, c:3}, {a:3, b:4, c:2}];
store(x, 'y');
```

and a data frame 'y' is made available in Python.

If you need to move Python data to Node, then presumably you are doing Python code - so the mechanism needs to be Python:

```python
store(df, 'z')
```

would be the nearest equivalent syntax? Or I could do `node.store(df,'z')` ?

**Comment by DTAIEB** [comment]
@glynnbird we should implement like the scala bridge and automatically import all the variables that we can bridge from the Notebook global scope. That way you don't need to use store on Python, just declare the variable in Python and start using it in Node

**Comment by glynnbird** [comment]
This feature is present in the new 0.2.0 release
