### ISSUE TITLE
Cannot run  node commands - a byte like object is required

### ISSUE THREAD

**Issue by elshor** [ibm-watson-data-lab/pixiedust_node#15]
Could not start a node command. Got the message that byte object is required. I installed jupyter using anaconda3. Here is how I fixed it
* Added encode when writing to stdin
* When reading from stdout, convert from byte to string
* Also needed to flush after writing to stdin

Let me know if you need it as a pull request

**Comment by glynnbird** [comment]
Are you running Python 3 @elshor?

**Comment by elshor** [comment]
yes

**Comment by glynnbird** [comment]
Should be fixed in the 0.1.7 release
