### ISSUE TITLE
Cleanup: terminate the pixie dust_node background process when the notebook server shuts down

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/pixiedust_node#23]
If one opens a notebook and imports the `pixie dust_node` package, a Node.js background process (`pixiedustNodeRel.js`) is launched.  This process currently remains running after the notebook server is shut down. If possible, we should terminate the process since it doesn't serve a purpose anymore at that point.

**Comment by glynnbird** [comment]
Fixed in 0.2.3
